# Generated by Django 5.0 on 2025-04-21 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=60, verbose_name='Автор')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2025)], verbose_name='Год издания')),
                ('publisher', models.CharField(max_length=50, verbose_name='Издательство')),
                ('edition', models.PositiveIntegerField(default=1, verbose_name='Номер издания')),
                ('additionally', models.TextField(blank=True, max_length=1000, verbose_name='Дополнительно')),
                ('cover', models.ImageField(blank=True, upload_to='covers/%Y/', verbose_name='Обложка')),
            ],
        ),
    ]
