# Generated by Django 5.0 on 2025-04-26 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name='Телефон')),
            ],
        ),
        migrations.AlterModelOptions(
            name='listbooks',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(verbose_name='Дата выдачи')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblio.listbooks')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblio.readers')),
            ],
        ),
    ]
