# Generated by Django 5.1.6 on 2025-05-10 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_readers_alter_listbooks_options_distribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Фамилия Имя гг-мм-дд рождения'),
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'verbose_name': 'Выдано книг', 'verbose_name_plural': 'Выдано книг'},
        ),
        migrations.AlterModelOptions(
            name='listbooks',
            options={'ordering': ['title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='distribution',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblio.listbooks', verbose_name='Название книги / авторы'),
        ),
        migrations.DeleteModel(
            name='Readers',
        ),
    ]
