# Generated by Django 5.0 on 2025-06-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_alter_distribution_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listbooks',
            name='additionally',
        ),
        migrations.AlterField(
            model_name='distribution',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.listbooks', verbose_name='Название книги / авторы'),
        ),
        migrations.CreateModel(
            name='NumberOfBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Количество')),
                ('additionally', models.TextField(blank=True, max_length=1000, verbose_name='Дополнительно')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblio.listbooks', verbose_name='Название книги / авторы')),
            ],
        ),
    ]
