# Generated by Django 5.1.6 on 2025-05-10 10:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
            },
        ),
    ]
