# Generated by Django 5.0 on 2025-05-20 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readers',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readers',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
