# Generated by Django 5.0 on 2025-05-20 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_readers_id_alter_readers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readers',
            name='phone',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
